apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testHelmNode
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hBarseghyanpin/testHelmNode
    path: nodeFold
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: testHelmNode-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true