apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-helmnode
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hBarseghyanpin/testHelmNode
    path: helm
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: test-helm-node-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true