---
# Source: nodejs/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myrelease-nodejs
  labels:
    chart: "nodejs-0.1.0"
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: nodejs
  selector:
    app: myrelease-nodejs
---
# Source: nodejs/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myrelease-nodejs
  labels:
    chart: "nodejs-0.1.0"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myrelease-nodejs
    spec:
      containers:
      - name: nodejs
        image: "har17bar/node:0.1.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m